HumanFriends/Controllers/AnimalController.cs
using HumanFriends.DAL.Interfaces;
using HumanFriends.Domain.Entity;
using HumanFriends.Domain.View;
using HumanFriends.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using static System.Net.Mime.MediaTypeNames;

namespace HumanFriends.Controllers
{
    public class AnimalController : Controller
    {

        private readonly IBaseService<Animal> _animalService;
        private readonly List<TypeAnimal> _typeAnimalRepository;
        private readonly List<ApplicabilityAnimal> _applicabilityAnimalRepository;
        private readonly List<ApplicabilityCommand> _applicabilityCommandRepository;
        private readonly List<Command> _commandRepository;


        public AnimalController(IBaseService<Animal> animalService,
                                IBaseRepository<TypeAnimal> typeAnimalRepository,
                                IBaseRepository<ApplicabilityAnimal> applicabilityAnimalRepository,
                                IBaseRepository<ApplicabilityCommand> applicabilityCommandRepository,
                                IBaseRepository<Command> commandRepository)
        {
            _animalService = animalService;
            _typeAnimalRepository = typeAnimalRepository.GetAll().ToList();
            _applicabilityAnimalRepository = applicabilityAnimalRepository.GetAll().ToList();
            _applicabilityCommandRepository = applicabilityCommandRepository.GetAll().ToList();
            _commandRepository = commandRepository.GetAll().ToList();

        }



        [HttpGet]
        public async Task<IActionResult> GetAnimals()
        {
            var response = await _animalService.GetAnimals();

            if (response.StatusCode == Entity.Enum.StatusCode.OK)
            {
                return View(response.Data.ToList());
            }
            return RedirectToAction("Error");
        }


        [HttpPost]
        public async Task<IActionResult> Delete(Animal animal)
        {
            var response = await _animalService.DeleteAnimal(animal.ID);
            
                return RedirectToAction("GetAnimals");
          
            //return RedirectToAction("Error");
        }



        [HttpGet]
        public IActionResult Save()
        {
            var animalView = new AnimalView();
            var typesAnimal = _typeAnimalRepository;
            var commandsAnimal = _commandRepository;
            animalView.TypeAnimalSelectList = new List<SelectListItem>();


            foreach (var type in typesAnimal)
            {
                animalView.TypeAnimalSelectList.Add(new SelectListItem { Text = type.Name, Value = ""+ type.ID });
            }
            animalView.CommandsAnimalSelect = new List<Command>();

            foreach (var command in commandsAnimal)
            {

                animalView.CommandsAnimalSelect.Add(command);
            }
            animalView.SelectedCommandsAnimalByID = new bool[animalView.CommandsAnimalSelect.Count];
            
            return View(animalView);
        }

        [HttpPost]
        public async Task<IActionResult> Save(AnimalView model)
        {
            Animal animal = new Animal() {
                Name = model.Name
        };
            animal.TypeAnimal = _typeAnimalRepository[model.SelectedTypeAnimal];
            animal.Birthday = model.Birthday;
            

            await _animalService.CreateAnimal(animal);
            return RedirectToAction("GetAnimals");
        }


    }
}

HumanFriends/Controllers/HomeController.cs
using HumanFriends.Domain.Entity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HumanFriends.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HumanFriends/Views/Animal/GetAnimals.cshtml
@using HumanFriends.Domain.Entity;
@model List<Animal>

@{
    ViewData["Title"] = "title";
    Layout = "_Layout";
}
<form asp-controller="Animal" asp-action="GetAnimals" method="get">
    <div class="mb-3">
    <table align="center">
        <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Birthday</td>
            <td>TypeAnimal</td>
            <td>ApplicabilityAnimal</td>
            <td>Delete</td>
        </tr>
    @foreach (var animal in Model)
        {
            <tr>
                <td>@animal.ID</td>
                <td>@animal.Name</td>
                <td>@animal.Birthday</td>
                <td>@animal.TypeAnimal.Name</td>
                <td>@animal.TypeAnimal.ApplicabilityAnimal.Name</td>
                <td>
                    <form asp-controller="Animal" asp-action="Delete" method="post">

                            <button type="submit" value="@animal.ID" class="btn btn-primary">
                                <input asp-for="@animal.ID" hidden/>Delete
                                </button>
                    </form>
                </td>
            </tr>
        }

    </table>
        </div>
</form>

HumanFriends/Views/Animal/Save.cshtml
@{
    ViewData["Title"] = "title";
    Layout = "_Layout";
}
@model HumanFriends.Domain.View.AnimalView




<form asp-controller="Animal" asp-action="Save" method="post">
    <div class="mb-3">
        <div class="form-group col-md-4">
            <label asp-for="@Model.Name" class="col-form-label text-black-50"></label>
            <input asp-for="@Model.Name" type="text" class="form-control">
        </div>
        <div class="form-group col-md-4">
            <label asp-for="@Model.Birthday" class="col-form-label text-black-50"></label>
            <input asp-for="@Model.Birthday" type="date" class="form-control" />
        </div>
        <div class="form-group col-md-4">
            <label class="col-form-label text-black-50"></label>
            <select class="form-select" asp-items="@Model.TypeAnimalSelectList" asp-for="SelectedTypeAnimal"></select>
        </div> 
        <div class="form-control">
            @for (int i = 0; i < Model.CommandsAnimalSelect.Count;i++)
            {
                <input asp-for="SelectedCommandsAnimalByID[i]" type="checkbox" />
                <label for="scales">@Model.CommandsAnimalSelect[i].Name</label>
            }
          
        </div> 
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

HumanFriends/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

HumanFriends/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HumanFriends</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HumanFriends.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HumanFriends</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="GetAnimals">All Animals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Save">Create Animals</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HumanFriends - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>